package com.mcaibot.companion;

import com.google.gson.JsonArray;
import com.google.gson.JsonObject;

import java.util.List;

public final class SkillRegistry {
    private static final List<SkillSpec> SKILLS = List.of(
            primitive("observe_environment", "Build a bounded ObservationFrame from live perception, recent memory, long-term map, resources, feedback, and available actions.",
                    strings("server player context is available"),
                    strings("fresh observation frame", "planner receives memory and feedback"),
                    strings("player", "npc", "worldKnowledge", "resources", "executionFeedback"),
                    strings(),
                    "BridgeContext/ObservationFrame",
                    "schema has actor, perception, memory, resources, feedback, capabilities, skills",
                    strings("reduce context detail", "ask player to retry if no player is online"),
                    true,
                    "safe"),
            primitive("report_resources", "Report NPC storage, approved nearby container resources, crafting materials, and blueprint material gaps.",
                    strings("server player context is available"),
                    strings("resource summary emitted", "planner receives material gaps"),
                    strings("resources", "tools", "crafting", "blueprints"),
                    strings(),
                    "ResourceAssessment.report",
                    "ActionResult observations.resources contains current resource snapshot",
                    strings("approve container materials", "gather missing materials", "ask player for alternate material"),
                    true,
                    "safe"),
            primitive("survival_assist", "Run the first vertical-slice survival policy: protect during danger, harvest mature crops, gather logs for early materials, or report the observed blocker.",
                    strings("spawned NPC", "player online", "survivalEnvironment snapshot available"),
                    strings("highest-priority survival action started or environment blocker reported"),
                    strings("survivalEnvironment", "nearbyEntities", "resources", "tools", "executionFeedback"),
                    strings("combat if danger is immediate", "world changes only through whitelisted survival actions"),
                    "SurvivalActions.survivalAssist",
                    "ActionResult includes survivalEnvironment observation and started/completed priority action",
                    strings("guard_player", "harvest_crops", "harvest_logs", "ask permission for destructive work"),
                    false,
                    "normal"),
            primitive("till_field", "Till a small bounded starter field near water using a hoe from NPC storage.",
                    strings("spawned NPC", "hoe in NPC storage", "nearby dirt or grass", "nearby water source"),
                    strings("watered farmland blocks created"),
                    strings("survivalEnvironment", "npc.inventory", "nearbyBlocks"),
                    strings("irreversible_block_change", "requires explicit player command or saved-plan permission"),
                    "SurvivalActions.tillField",
                    "ActionResult effects.tilledBlocks > 0 or blocker explains missing hoe/water/soil",
                    strings("craft or provide hoe", "move near water and dirt", "ask player for field location"),
                    false,
                    "destructive"),
            primitive("plant_crop", "Plant wheat, carrot, potato, or beetroot crops on nearby empty farmland from NPC storage.",
                    strings("spawned NPC", "matching seeds/crop item in NPC storage", "empty farmland nearby"),
                    strings("crop blocks planted"),
                    strings("survivalEnvironment", "npc.inventory", "nearbyBlocks"),
                    strings("uses only NPC storage"),
                    "SurvivalActions.plantCrop",
                    "ActionResult effects.planted > 0 or blocker explains missing seeds/farmland",
                    strings("till_field", "collect seeds", "ask for crop type"),
                    false,
                    "normal"),
            primitive("harvest_crops", "Harvest mature nearby crops and start collecting dropped items.",
                    strings("spawned NPC", "mature crops nearby"),
                    strings("mature crops broken and drops collection started"),
                    strings("survivalEnvironment", "nearbyBlocks", "npc"),
                    strings("safe autonomous action for mature crops only"),
                    "SurvivalActions.harvestCrops",
                    "ActionResult effects.harvested > 0 and collect_items task starts, or no mature crop blocker",
                    strings("move near mature crops", "plant_crop", "report_environment"),
                    true,
                    "safe"),
            primitive("hunt_food_animal", "Hunt one nearby adult wild food animal while avoiding babies, named, leashed, tameable, or fenced animals.",
                    strings("spawned NPC", "adult wild cow/sheep/pig/chicken/rabbit nearby", "player permission for hunting"),
                    strings("NPC approaches or attacks one safe food animal target"),
                    strings("survivalEnvironment", "nearbyEntities", "npc.equipment"),
                    strings("combat", "requires explicit player command or saved-plan permission", "never attacks protected animals"),
                    "SurvivalActions.huntFoodAnimal",
                    "ActionResult target is safe food animal or blocker reports no safe target",
                    strings("move near wild food animals", "feed_animal instead", "ask player to confirm hunting"),
                    false,
                    "combat"),
            primitive("feed_animal", "Feed a nearby matching animal using valid food from NPC storage.",
                    strings("spawned NPC", "matching animal nearby", "accepted animal food in NPC storage"),
                    strings("animal receives food and may enter love/taming flow depending on species"),
                    strings("nearbyEntities", "npc.inventory"),
                    strings("uses only NPC storage"),
                    "SurvivalActions.feedAnimal",
                    "ActionResult names animal and consumed feed item or reports missing food/target",
                    strings("collect/provide feed", "move closer", "specify animal type"),
                    false,
                    "normal"),
            primitive("breed_animals", "Feed two nearby adult unprotected matching animals for breeding using NPC storage feed.",
                    strings("spawned NPC", "two adult unprotected matching animals nearby", "two matching food items in NPC storage"),
                    strings("two animals are fed for breeding"),
                    strings("nearbyEntities", "npc.inventory"),
                    strings("uses only NPC storage", "avoids babies/named/leashed/tameable/fenced animals"),
                    "SurvivalActions.breedAnimals",
                    "ActionResult effects.fed == 2 or blocker reports missing pair/feed",
                    strings("move near two animals", "collect/provide feed", "ask player for animal type"),
                    false,
                    "normal"),
            primitive("tame_animal", "Tame a supported nearby animal from NPC storage items; first version supports wolves with bones and cats with cod/salmon.",
                    strings("spawned NPC", "supported tameable nearby", "taming item in NPC storage"),
                    strings("animal becomes tamed or already-tame state is reported"),
                    strings("nearbyEntities", "npc.inventory"),
                    strings("uses only NPC storage", "requires explicit player command"),
                    "SurvivalActions.tameAnimal",
                    "ActionResult reports tamed/already tame or missing target/item",
                    strings("provide bones or fish", "move near wolf/cat", "ask which animal"),
                    false,
                    "normal"),
            primitive("build_redstone_template", "Build a low-risk redstone template through the machine template system.",
                    strings("spawned NPC", "approved redstone template", "required materials in NPC storage or approved containers", "clear target space"),
                    strings("pressure/button/lever door or simple lamp-switch template placed at a verified player-facing anchor"),
                    strings("resources", "nearbyBlocks", "npc.inventory", "survivalEnvironment", "machineTemplates"),
                    strings("irreversible_block_change", "requires explicit player command or saved-plan permission", "template-only redstone", "does not build high-frequency clocks"),
                    "SurvivalActions.buildRedstoneTemplate",
                    "ActionResult names the redstone template or blocker explains missing materials/space",
                    strings("craft/provide redstone parts", "move to clear flat area", "ask for another approved template"),
                    false,
                    "destructive"),
            primitive("preview_machine", "Preview a deterministic redstone or vanilla survival-machine template without changing the world.",
                    strings("machine/template intent", "player online in same dimension"),
                    strings("risk summary, material budget, footprint, entity needs, and site safety are reported"),
                    strings("machineTemplates", "resources", "nearbyBlocks", "survivalEnvironment"),
                    strings("no_world_change", "high-risk machines require saved-plan authorization before build"),
                    "MachineBuildController.previewMachine",
                    "ActionResult includes safety, materialPlan, entityRequirements, and testProcedure",
                    strings("move to clear site", "collect/provide missing materials", "authorize exact plan before building high-risk machine"),
                    true,
                    "safe"),
            primitive("authorize_machine_plan", "Authorize the exact previewed high-risk machine plan for a limited time.",
                    strings("machine/template intent", "player confirmation after preview", "same anchor/dimension/facing"),
                    strings("saved authorization is bound to player, machine id, dimension, anchor, facing, range, TTL, and risk"),
                    strings("machineTemplates", "player", "position"),
                    strings("no_world_change", "authorization expires", "build must match authorization exactly"),
                    "MachineBuildController.authorizeMachinePlan",
                    "ActionResult includes authorization snapshot and expiry",
                    strings("preview first", "keep anchor/facing unchanged", "re-authorize if plan changes"),
                    true,
                    "normal"),
            primitive("build_machine", "Build an authorized deterministic vanilla redstone/survival-machine template by direct placement while consuming real materials.",
                    strings("spawned NPC", "matching saved authorization for high-risk templates", "safe build volume", "materials in NPC storage or approved containers"),
                    strings("machine blocks are placed, materials consumed, and verifier reports complete or waiting-for-entities"),
                    strings("machineTemplates", "npc.inventory", "nearbyContainers", "nearbyBlocks", "nearbyEntities"),
                    strings("irreversible_block_change", "does not use player inventory", "does not spawn villagers or monsters", "blocks protected/base/core blocks", "no TNT dupers, chunk loaders, raid farms, wither machines, item-duplication exploits, or high-frequency clocks"),
                    "MachineBuildController.buildMachine",
                    "ActionResult includes placed/skipped counts, material consumption, and verifier state",
                    strings("preview and authorize exact plan", "collect/provide missing materials", "move to clear site", "supply/capture required entities separately"),
                    false,
                    "destructive"),
            primitive("test_machine", "Verify an existing machine template without changing the world.",
                    strings("machine/template intent", "player online in same dimension", "anchor/facing"),
                    strings("required blocks, fluids, redstone, collection paths, and entity readiness are checked"),
                    strings("machineTemplates", "nearbyBlocks", "nearbyEntities"),
                    strings("no_world_change", "missing villagers/zombies returns WAITING_FOR_ENTITIES rather than structure failure"),
                    "MachineBuildController.testMachine",
                    "ActionResult succeeds for complete structure or WAITING_FOR_ENTITIES; blockers name missing blocks",
                    strings("repair missing blocks", "supply required entities", "rerun test_machine"),
                    true,
                    "safe"),
            primitive("cancel_machine_build", "Cancel the current machine build authorization.",
                    strings("player online"),
                    strings("stored authorization removed or idle state reported"),
                    strings("authorizationSnapshot"),
                    strings("no_world_change"),
                    "MachineBuildController.cancelMachineBuild",
                    "ActionResult reports MACHINE_BUILD_CANCELLED or no active authorization",
                    strings("preview and authorize a new machine plan"),
                    true,
                    "normal"),
            primitive("move_to", "Move the active NPC to an exact world position using normal navigation.",
                    strings("spawned NPC", "exact x/y/z target"),
                    strings("NPC starts pathing to target"),
                    strings("player", "npc", "position"),
                    strings("bounded movement"),
                    "NpcManager.goTo",
                    "NPC task/path state reports movement or blocker",
                    strings("recover_mobility", "ask for closer/reachable target", "place scaffold/path block if allowed by runtime"),
                    false,
                    "normal"),
            primitive("follow_player", "Follow the owner/player until stopped or replaced by another task.",
                    strings("spawned NPC", "target player online"),
                    strings("NPC follows player"),
                    strings("player", "npc"),
                    strings(),
                    "NpcManager.follow",
                    "NPC follow state points at player",
                    strings("come_to_player", "recover_mobility"),
                    true,
                    "safe"),
            primitive("inspect_block", "Inspect an exact block position, including id, hardness, block entity, tool needs, and breakability.",
                    strings("exact block position", "target within primitive range"),
                    strings("block report emitted", "world memory can store block facts"),
                    strings("player", "position", "nearbyBlocks"),
                    strings(),
                    "NpcManager.inspectBlock",
                    "chat/task feedback contains inspected block facts",
                    strings("ask for coordinates", "move closer"),
                    true,
                    "safe"),
            primitive("break_block", "Break one exact block through player-like reach, facing, timed mining, tool validity, and durability checks.",
                    strings("spawned NPC", "exact block position", "block within range", "runtime has usable tool or hand break is valid"),
                    strings("target block removed or blocker reported", "drops can be collected"),
                    strings("player", "npc", "tools", "position"),
                    strings("irreversible_block_change"),
                    "NpcManager.breakBlockAt",
                    "block changed, mining task completed, or structured blocker returned",
                    strings("inspect_block", "craft/equip required tool", "recover_mobility", "ask permission for destructive edit"),
                    false,
                    "destructive"),
            primitive("place_block", "Place one exact block using NPC storage, collision checks, reach, support, and real placement rules.",
                    strings("spawned NPC", "exact block position", "placeable block in NPC storage or approved container materials"),
                    strings("block placed or blocker reported"),
                    strings("player", "npc", "resources", "position"),
                    strings("irreversible_block_change"),
                    "NpcManager.placeBlockAt",
                    "block exists at target and matches requested material, or blocker explains why not",
                    strings("collect/craft placeable blocks", "ask for chest approval", "choose adjacent support block"),
                    false,
                    "destructive"),
            primitive("collect_items", "Collect nearby dropped item entities into NPC storage.",
                    strings("spawned NPC"),
                    strings("nearby drops picked up", "NPC storage updated"),
                    strings("nearbyEntities", "npc"),
                    strings(),
                    "NpcManager.collectItems",
                    "collector task finishes or reports blockers",
                    strings("move closer", "increase bounded radius", "report no drops"),
                    true,
                    "safe"),
            primitive("harvest_logs", "Gather nearby logs with real axe/tool rules, overhead-log handling, bounded following, scaffold repair, and drop collection.",
                    strings("spawned NPC", "logs nearby or bounded search/follow is acceptable", "usable/craftable axe preferred"),
                    strings("logs harvested", "drops collected", "resource memory updated"),
                    strings("nearbyBlocks", "worldKnowledge", "tools", "resources"),
                    strings("bounded exploration"),
                    "NpcManager.harvestLogs",
                    "task feedback reports logs harvested, completion, or a blocker",
                    strings("prepare_axe", "recover_mobility", "collect_items", "ask for scaffold blocks/chest approval"),
                    false,
                    "normal"),
            primitive("salvage_nearby_wood_structure", "Reclaim wooden structural blocks around the player's current position without exact coordinates, skipping block entities such as chests.",
                    strings("spawned NPC", "player stands inside or next to target wooden structure", "usable/craftable axe", "explicit destructive salvage request"),
                    strings("bounded wooden structural blocks broken", "drops collected", "block entities skipped"),
                    strings("player", "npc", "nearbyBlocks", "tools"),
                    strings("irreversible_block_change", "bounded_radius", "does_not_use_player_inventory", "skips_block_entities"),
                    "NpcManager.salvageNearbyWoodStructure",
                    "task feedback reports salvaged blocks, collection started, or blocker",
                    strings("stand inside/next to target structure", "prepare_axe", "recover_mobility", "use exact break_block for one block"),
                    false,
                    "destructive"),
            primitive("prepare_basic_tools", "Ensure the active NPC has a requested basic axe and/or pickaxe using NPC storage and approved nearby containers only.",
                    strings("spawned NPC", "tool materials in NPC storage or approved nearby containers if crafting is needed"),
                    strings("requested basic tools exist or blocker reports missing materials"),
                    strings("npc.inventory", "tools", "crafting", "resources"),
                    strings(),
                    "NpcManager.prepareBasicTools",
                    "ActionResult success when required tools are prepared, otherwise structured blocker",
                    strings("gather logs/planks/sticks/cobblestone", "approve nearby chest materials", "ask player for tool materials"),
                    false,
                    "normal"),
            primitive("mine_nearby_ore", "Mine exposed nearby ore with pickaxe tier and durability checks.",
                    strings("spawned NPC", "exposed ore nearby or remembered within bounded search", "usable/craftable pickaxe"),
                    strings("ore mined", "drops collected"),
                    strings("nearbyBlocks", "worldKnowledge", "tools", "resources"),
                    strings("bounded exploration"),
                    "NpcManager.mineOres",
                    "task feedback reports mined ore or blocker",
                    strings("prepare_pickaxe", "inspect_block", "recover_mobility", "ask for safer target"),
                    false,
                    "normal"),
            primitive("gather_stone", "Gather reachable stone/cobblestone-like material with real pickaxe, timed breaking, tool checks, and bounded radius.",
                    strings("spawned NPC", "reachable exposed stone/cobblestone/deepslate/blackstone nearby", "usable/craftable pickaxe"),
                    strings("stone/cobblestone-like drops produced for stone tools or building", "drops can be collected"),
                    strings("nearbyBlocks", "worldKnowledge", "tools", "resources"),
                    strings("bounded exploration"),
                    "NpcManager.gatherStone",
                    "task feedback reports stone blocks broken, completion, or blocker",
                    strings("prepare_pickaxe", "collect_items", "inspect_block", "recover_mobility", "ask to approve chest materials or move near stone"),
                    false,
                    "normal"),
            primitive("craft_item", "Craft supported basic items from NPC storage without consuming player inventory.",
                    strings("spawned NPC", "supported recipe", "ingredients in NPC storage"),
                    strings("crafted items added to NPC storage"),
                    strings("resources", "crafting", "tools"),
                    strings(),
                    "NpcManager.craftItem",
                    "NPC storage count increases or recipe blocker reported",
                    strings("gather ingredients", "use craft_at_table", "ask for chest approval if only containers have materials"),
                    false,
                    "normal"),
            primitive("craft_at_table", "Move to a nearby reachable crafting table and craft supported basic items from NPC storage.",
                    strings("spawned NPC", "nearby reachable crafting table", "supported recipe", "ingredients in NPC storage"),
                    strings("crafted items added to NPC storage"),
                    strings("crafting", "nearbyBlocks", "resources"),
                    strings(),
                    "NpcManager.craftAtNearbyTable",
                    "crafted item exists or table/material blocker reported",
                    strings("craft_item fallback", "move closer to table", "ask for chest approval"),
                    false,
                    "normal"),
            primitive("equip_item", "Equip the best available armor, weapon, shield, or relevant tool from NPC storage.",
                    strings("spawned AI NPC", "equipment exists in NPC storage"),
                    strings("NPC equipment/mainhand updated"),
                    strings("npc.inventory", "npc.equipment", "tools"),
                    strings(),
                    "NpcManager.autoEquipNow",
                    "equipment snapshot improves or reports already best",
                    strings("craft tools", "collect equipment", "report no gear"),
                    true,
                    "safe"),
            primitive("open_container", "Inspect nearby accessible container rules and contents summary without taking items.",
                    strings("nearby container"),
                    strings("container summary reported"),
                    strings("nearbyContainers", "resources"),
                    strings(),
                    "NpcManager.chestStatus",
                    "container report includes approval policy and nearby contents",
                    strings("move closer", "ask player which container"),
                    true,
                    "safe"),
            primitive("withdraw_from_chest", "Take an explicit item/count from a nearby accessible container into NPC storage.",
                    strings("spawned AI NPC", "nearby accessible container", "explicit item", "explicit or bounded count"),
                    strings("NPC storage receives item", "container count decreases"),
                    strings("nearbyContainers", "resources"),
                    strings("container_transfer", "player approval for implicit material use"),
                    "NpcManager.withdrawFromNearbyChest",
                    "NPC storage change or blocker reported",
                    strings("ask for item/count", "ask for approval", "move closer to container"),
                    false,
                    "permissioned"),
            primitive("deposit_to_chest", "Deposit an explicit item/count or all NPC storage into a nearby accessible container.",
                    strings("spawned AI NPC", "nearby accessible container"),
                    strings("container receives items", "NPC storage decreases"),
                    strings("nearbyContainers", "npc.inventory"),
                    strings("container_transfer"),
                    "NpcManager.depositItemToNearbyChest/depositNpcStorageToNearbyChest",
                    "container transfer succeeds or blocker reported",
                    strings("move closer", "ask for item/count if needed"),
                    false,
                    "permissioned"),
            primitive("attack_entity", "Attack hostile non-player entities threatening the protected player. Player entities are never valid targets.",
                    strings("spawned NPC", "hostile mob target", "target is not a player"),
                    strings("hostile mob attacked or guard task reports blocker"),
                    strings("nearbyEntities", "danger", "npc.equipment"),
                    strings("combat"),
                    "ProtectionManager",
                    "guard feedback reports hostile engagement",
                    strings("equip_best_gear", "retreat/report if unsafe", "ask before risky combat"),
                    false,
                    "combat"),
            primitive("guard_player", "Default protection mode around the owner/player; attacks hostile mobs but never players.",
                    strings("spawned NPC", "player online"),
                    strings("guard mode active"),
                    strings("player", "nearbyEntities", "danger"),
                    strings("combat"),
                    "ProtectionManager.start",
                    "protection state active",
                    strings("equip_best_gear", "stop_guard", "report unsafe combat"),
                    true,
                    "combat"),
            primitive("gather_materials", "Acquire requested build materials with structured source priority: NPC storage, approved containers, known resource hints, then bounded same-dimension scouting.",
                    strings("spawned NPC", "material category logs|stone|sand|dirt|glass_like|placeable_blocks", "bounded count"),
                    strings("requested material count is available, or a gather task starts, or blocker explains missing source/tool"),
                    strings("resources", "worldKnowledge.resourceHints", "travelPolicy", "npc.inventory"),
                    strings("bounded_exploration", "does_not_use_player_inventory", "container_materials_require_approval"),
                    "MaterialGatherer.gatherMaterials",
                    "ActionResult contains collected/missing/source/visitedTargets/blocker/nextRepair",
                    strings("collect_items", "approve_chest_materials", "move near resource", "retry build_structure after collection"),
                    false,
                    "normal"),
            primitive("preview_structure", "Preview an internal blueprint template, material budget, role counts, placement queue, travel policy, and site blockers without modifying the world.",
                    strings("structure intent or template id", "player-relative or explicit anchor"),
                    strings("blueprint preview and material/site plan returned"),
                    strings("structureBlueprints", "resources", "travelPolicy", "position"),
                    strings("no_world_change"),
                    "StructureBuildController.previewStructure",
                    "ActionResult includes blueprint, siteCheck, and materialPlan",
                    strings("build_structure", "gather_materials", "choose another site/template"),
                    true,
                    "safe"),
            primitive("build_structure", "Build a deterministic internal blueprint template using safe site checks, role-based block palettes, automatic material-gather start when short, and optional decoration skips.",
                    strings("spawned NPC", "approved template", "safe build anchor", "placeable blocks or autoGather permission"),
                    strings("structure placed, material gather starts, or blocker explains missing material/site issue"),
                    strings("structureBlueprints", "resources", "travelPolicy", "npc.inventory", "nearbyContainers"),
                    strings("irreversible_block_change", "does_not_clear_player_base_blocks", "container_materials_require_approval"),
                    "StructureBuildController.buildStructure",
                    "ActionResult reports placed/skipped/missing/blockers with blueprint id",
                    strings("gather_materials", "approve_chest_materials", "preview_structure", "choose safer site"),
                    false,
                    "destructive"),
            primitive("cancel_structure", "Cancel an active structure/build-related task and stop NPC runtime movement.",
                    strings("spawned NPC"),
                    strings("active structure task stopped if present"),
                    strings("npc.runtime"),
                    strings("safe_stop"),
                    "StructureBuildController.cancelStructure",
                    "NPC runtime task is stopped or already idle",
                    strings("preview_structure", "build_structure"),
                    true,
                    "safe"),
            primitive("build_basic_house", "Start the basic shelter builder at a verified anchor using NPC storage, gathered blocks, and approved container blocks only.",
                    strings("spawned NPC", "enough placeable blocks", "safe build anchor or player-relative default"),
                    strings("basic shelter builder starts or blocker reports material/site issue"),
                    strings("resources", "blueprints", "npc", "position"),
                    strings("irreversible_block_change"),
                    "NpcManager.buildBasicHouse",
                    "task feedback reports build_basic_house completion or blocker",
                    strings("report_resources", "gather_materials", "choose safer site", "ask for material approval"),
                    false,
                    "destructive"),
            primitive("build_large_house", "Start the larger 7x7 house builder at a verified anchor using NPC storage, gathered blocks, and approved container blocks only.",
                    strings("spawned NPC", "safe build anchor or player-relative default", "placeable blocks available or bounded wood gathering is acceptable"),
                    strings("large house builder starts or blocker reports material/site issue", "builder may gather more wood within bounded rounds before resuming"),
                    strings("resources", "blueprints", "npc", "position"),
                    strings("irreversible_block_change"),
                    "NpcManager.buildLargeHouse",
                    "task feedback reports build_large_house completion, material gathering, or blocker",
                    strings("report_resources", "harvest_logs", "collect_items", "ask for material approval", "choose safer site"),
                    false,
                    "destructive"),
            primitive("repair_structure", "Repair a nearby existing house/shelter shell by scanning the perimeter, inferring dominant wall material, finding a two-block doorway, crafting a door if needed, and placing missing wall/door blocks.",
                    strings("spawned NPC", "player stands inside or near the damaged structure", "clear nearby building shell", "repair blocks or craftable door materials in NPC storage or approved nearby containers"),
                    strings("missing wall blocks and clear missing doorway are patched", "blocker reports unclear structure, missing material, missing door materials, or pathing issue"),
                    strings("nearbyBlocks", "resources", "npc", "structureBounds"),
                    strings("irreversible_block_change", "container approval if using nearby containers"),
                    "NpcManager.repairNearbyStructure",
                    "task feedback reports repair_structure completion or a structured blocker",
                    strings("stand closer to the damaged house", "approve nearby chest materials", "gather/craft matching materials", "provide exact target coordinates if the shell is ambiguous"),
                    false,
                    "destructive"),
            primitive("report_modded_nearby", "Summarize Create/Create Aeronautics/modded blocks and safe interaction limits nearby.",
                    strings("modded snapshot available"),
                    strings("modded machine report emitted"),
                    strings("modded", "nearbyBlocks"),
                    strings(),
                    "ModInteractionManager.reportNearby",
                    "report lists namespaces/categories/positions",
                    strings("inspect_mod_block", "ask for exact target"),
                    true,
                    "safe"),
            primitive("inspect_mod_block", "Inspect an exact modded block, block entity, inventory hints, properties, and safe wrenchability.",
                    strings("exact block position"),
                    strings("modded block details reported"),
                    strings("modded", "position"),
                    strings(),
                    "ModInteractionManager.inspectBlock",
                    "report includes block id, namespace, properties, entity data",
                    strings("report_modded_nearby", "ask for coordinates"),
                    true,
                    "safe"),
            primitive("use_mod_wrench", "Right-click a specific Create-family block with a wrench if available; no GUI/filter/flight automation.",
                    strings("exact block position", "wrench available", "player explicitly requested safe wrench operation"),
                    strings("target block receives wrench interaction or blocker"),
                    strings("modded", "position", "tools"),
                    strings("modded_machine_operation"),
                    "ModInteractionManager.useWrench",
                    "wrench result reported",
                    strings("inspect_mod_block", "ask for exact coordinates", "ask for safety confirmation"),
                    false,
                    "permissioned"),
            primitive("recover_mobility", "Recover from navigation blockers by reporting path issue, retrying bounded movement, or using placeable scaffold/path blocks when runtime permits.",
                    strings("mobility blocker in feedback"),
                    strings("NPC unstuck or clear blocker reported"),
                    strings("executionFeedback", "latestTaskResults", "resources"),
                    strings("place_block_if_needed"),
                    "Npc task runtime repair strategies",
                    "feedback no longer repeats the same stuck code, or task reports repair exhausted",
                    strings("ask for scaffold blocks", "ask player to move closer", "cancel/replan"),
                    false,
                    "normal"),
            compound("gather_materials", "Plan and execute bounded resource acquisition without player inventory: inspect resources, gather safe nearby materials, collect drops, and report gaps.",
                    strings("goal material list", "bounded search radius/duration"),
                    strings("NPC storage has requested materials or blocker explains missing materials"),
                    strings("ObservationFrame.resources", "ObservationFrame.memory", "SkillRegistry"),
                    strings("bounded exploration", "chest approval for containers"),
                    strings("observe_environment", "harvest_logs", "gather_stone", "mine_nearby_ore", "collect_items", "craft_item"),
                    "material counts satisfy success criteria",
                    strings("convert logs to planks", "prepare required tool", "gather stone for stone tools", "ask chest approval", "ask player for alternate material"),
                    false,
                    "normal"),
            compound("prepare_tools", "Ensure the NPC has required basic tools by checking storage, crafting, equipping, and reporting missing ingredients.",
                    strings("task declares required tool category"),
                    strings("required tool exists and is equipped or blocker reports missing ingredients/station"),
                    strings("tools", "crafting", "resources"),
                    strings(),
                    strings("craft_item", "craft_at_table", "equip_item"),
                    "ToolSummary reports usable tool",
                    strings("gather wood/stone", "use approved container materials", "ask for advanced tool"),
                    false,
                    "normal"),
            compound("craft_basic_items", "Craft common early-game items the runtime actually supports: planks, sticks, wooden/stone axes, wooden/stone pickaxes, and basic tool sets.",
                    strings("supported primitive recipe", "materials in NPC storage or approved nearby containers"),
                    strings("requested basic item exists in NPC storage or blocker explains missing ingredients"),
                    strings("crafting", "resources", "tools", "nearbyContainers"),
                    strings("container approval if using nearby containers automatically"),
                    strings("report_crafting", "gather_materials", "craft_item", "craft_at_table", "equip_item"),
                    "crafted item count increases, tool readiness improves, or blocker is structured",
                    strings("gather wood", "gather stone", "collect drops", "ask chest approval", "ask for unsupported recipe clarification"),
                    false,
                    "normal"),
            compound("mine_resources", "Prepare a pickaxe, mine bounded exposed resources such as ore, collect drops, and report blockers instead of tunneling blindly.",
                    strings("spawned NPC", "reachable exposed ore/resource block or remembered resource hint", "usable/craftable pickaxe"),
                    strings("resource drops collected or no-resource blocker reported"),
                    strings("nearbyBlocks", "worldKnowledge", "tools", "resources"),
                    strings("bounded exploration"),
                    strings("observe_environment", "prepare_tools", "mine_nearby_ore", "collect_items", "report_resources"),
                    "ore/resource drop count increases or search budget is exhausted",
                    strings("prepare_pickaxe", "gather_stone", "recover_mobility", "ask player to move near target vein"),
                    false,
                    "normal"),
            compound("manage_storage", "Move NPC-held items into nearby containers, inspect container rules, withdraw explicit approved items, and never consume player inventory.",
                    strings("spawned storage-capable NPC", "nearby accessible container for transfer actions"),
                    strings("NPC storage/container state changes or a permission/count blocker is reported"),
                    strings("npc.inventory", "nearbyContainers", "resources", "policies"),
                    strings("container_transfer", "player approval for implicit material use"),
                    strings("open_container", "deposit_to_chest", "withdraw_from_chest", "report_resources"),
                    "container/NPC storage counts reflect requested transfer",
                    strings("ask item/count", "ask approval", "move closer to container", "deposit overflow only"),
                    false,
                    "permissioned"),
            compound("survival_assist", "Cover common survival support: guard the player, equip gear, gather basic resources, build a small shelter, collect drops, and report danger.",
                    strings("player online", "spawned NPC"),
                    strings("player threat reduced, shelter/resource support started, or clear blocker reported"),
                    strings("danger", "nearbyEntities", "resources", "tools", "npc.equipment"),
                    strings("combat", "irreversible_block_change for shelter building"),
                    strings("observe_environment", "equip_item", "guard_player", "gather_materials", "build_structure", "collect_items"),
                    "guard state active, useful survival task started/completed, or blocker has suggested repair",
                    strings("ask whether to build/gather/guard when ambiguous", "never attack players", "use nearby chest only after approval"),
                    false,
                    "combat"),
            compound("build_structure", "Build from a task graph and blueprint by verifying site, materials, placement order, collision, scaffold needs, and rollback/stop conditions.",
                    strings("blueprint or structure intent", "site/material constraints clarified enough"),
                    strings("structure blocks placed or blocker includes missing material/site issue"),
                    strings("ObservationFrame", "blueprints", "resources", "SkillRegistry"),
                    strings("irreversible_block_change", "container approval if needed"),
                    strings("observe_environment", "gather_materials", "craft_item", "place_block", "recover_mobility"),
                    "blueprint missing-block count reaches zero or acceptable partial criteria",
                    strings("gather more blocks", "convert logs to planks", "ask location/style/material clarification", "pause for approval"),
                    false,
                    "destructive"),
            compound("protect_player", "Maintain default guard behavior: scan threats, equip gear, attack hostile mobs only, and report danger.",
                    strings("player online", "spawned NPC"),
                    strings("player threat reduced or guard reports unsafe blocker"),
                    strings("nearbyEntities", "danger", "equipment"),
                    strings("combat"),
                    strings("observe_environment", "equip_item", "guard_player", "attack_entity"),
                    "ProtectionManager state and feedback",
                    strings("retreat/report if outmatched", "never attack players", "ask before risky combat"),
                    true,
                    "combat"),
            compound("explore_bounded", "Scout within explicit budget to extend long-term map with resources, containers, dangers, and landmarks.",
                    strings("search goal", "distance/time budget"),
                    strings("long-term map gains observations or search reports exhausted"),
                    strings("worldKnowledge", "player", "npc"),
                    strings("bounded exploration"),
                    strings("move_to", "observe_environment", "recover_mobility"),
                    "observedAreas/resourceHints/containerHints updated or budget exhausted",
                    strings("return to player", "ask to extend budget", "report no result"),
                    false,
                    "normal"),
            compound("coordinate_team", "Assign a task graph across multiple NPCs through a shared team blackboard when the player selects one, several, or all NPCs.",
                    strings("participants selected or clarified", "skills are compatible with parallel policy"),
                    strings("subtasks assigned or clarification asked"),
                    strings("npc.all", "availablePersonas", "SkillRegistry", "TaskGraph"),
                    strings("multi_npc_coordination"),
                    strings("targetScope", "profileId", "PlanManager"),
                    "task graph participant fields match selected NPCs",
                    strings("ask which NPC", "serialize unsafe work", "report unsupported parallel action"),
                    false,
                    "normal")
    );

    private SkillRegistry() {
    }

    public static JsonObject catalogJson() {
        JsonObject root = new JsonObject();
        root.addProperty("schemaVersion", "mc-agent-skill-registry-v1");
        root.addProperty("plannerContract", "SkillSpec(preconditions,effects,requiredContext,permissions,executor,verifier,repairStrategies)");
        JsonArray skills = new JsonArray();
        for (SkillSpec skill : SKILLS) {
            skills.add(skill.toJson());
        }
        root.add("skills", skills);
        return root;
    }

    public static JsonArray actionPrimitivesJson() {
        JsonArray primitives = new JsonArray();
        for (SkillSpec skill : SKILLS) {
            if (!"primitive".equals(skill.type())) {
                continue;
            }
            JsonObject json = new JsonObject();
            json.addProperty("name", skill.name());
            json.addProperty("executor", skill.executor());
            json.addProperty("safetyLevel", skill.safetyLevel());
            json.add("requiredContext", skill.requiredContext().deepCopy());
            json.add("permissions", skill.permissions().deepCopy());
            json.add("repairStrategies", skill.repairStrategies().deepCopy());
            primitives.add(json);
        }
        return primitives;
    }

    public static int skillCount() {
        return SKILLS.size();
    }

    public static boolean hasSkill(String name) {
        String normalized = normalize(name);
        if (normalized.isBlank()) {
            return false;
        }
        for (SkillSpec skill : SKILLS) {
            if (skill.name().equals(normalized)) {
                return true;
            }
        }
        return false;
    }

    private static SkillSpec primitive(
            String name,
            String description,
            JsonArray preconditions,
            JsonArray effects,
            JsonArray requiredContext,
            JsonArray permissions,
            String executor,
            String verifier,
            JsonArray repairStrategies,
            boolean parallelSafe,
            String safetyLevel
    ) {
        return new SkillSpec(name, "primitive", description, preconditions, effects, requiredContext, permissions, executor, verifier, repairStrategies, parallelSafe, safetyLevel);
    }

    private static SkillSpec compound(
            String name,
            String description,
            JsonArray preconditions,
            JsonArray effects,
            JsonArray requiredContext,
            JsonArray permissions,
            JsonArray executors,
            String verifier,
            JsonArray repairStrategies,
            boolean parallelSafe,
            String safetyLevel
    ) {
        return new SkillSpec(name, "compound", description, preconditions, effects, requiredContext, permissions, join(executors), verifier, repairStrategies, parallelSafe, safetyLevel);
    }

    private static JsonArray strings(String... values) {
        return AgentJson.strings(values);
    }

    private static String join(JsonArray values) {
        StringBuilder builder = new StringBuilder();
        for (int index = 0; index < values.size(); index++) {
            if (index > 0) {
                builder.append(" -> ");
            }
            builder.append(values.get(index).getAsString());
        }
        return builder.toString();
    }

    private static String normalize(String value) {
        return value == null ? "" : value.trim().toLowerCase().replace('-', '_').replace(' ', '_');
    }
}
